### ISSUE TITLE
Fatal error, unable to use

### ISSUE THREAD

**Issue by limycenter** [xemulat/XToolbox#11]
I am using a mini-laptop device with win11 pre-installed, updated, scanned.

When i run the .exe as administrator it errors out.  i had to be johnny quick fingers to quickly printscrn to see the details which are shown below.

Device is a G{D WIN MAX 2 if that matters.

Thanks for the awesome program, seriously love  it

![image](https://user-images.githubusercontent.com/84792179/204086027-a4e51645-33d1-4fb5-955e-400b5f676c0a.png)

**Comment by xemulat** [comment]
I think it tried to divide your disk usage space using dusage, try cleaning your trash files.

**Comment by limycenter** [comment]
i discovered the issue.  this must be placed and run from the OS drive partition

i was running from a data partition

**Comment by xemulat** [comment]
Ahhhhh, maybe the program tried to access data from the C drive being on the D drive

**Comment by xemulat** [comment]
Windows is just too protective lol

**Comment by xemulat** [comment]
Issue marked as fixed

+ Fixed in v2
