### ISSUE TITLE
Can't go 10 and up

### ISSUE THREAD

**Issue by Semedicarota** [xemulat/XToolbox#12]
If you do D10/11/12... it downloads the first tool of the colomn. 
![Screenshot_20221223_174422](https://user-images.githubusercontent.com/120989854/209371056-a1bf9533-9383-4544-ad89-090efc22de2b.png)

**Comment by Semedicarota** [comment]
I think this is because it starts with 1 so it download the first.

**Comment by xemulat** [comment]
Fixed in v2.2, the bug was reported in my Discord.
