### ISSUE TITLE
Python won't install

### ISSUE THREAD

**Issue by denniskalpedis** [xemulat/XToolbox#13]
**Describe the bug**
python should be "o5" but says command not found

**To Reproduce**
type "o5"

**Expected behavior**
install python

**Additional context**
https://github.com/xemulat/XToolbox/blob/main/XTBox.py#L522
line 522 on on XTBox.py has a 2nd "o4" instead of "o5"

**Comment by xemulat** [comment]
shit

**Comment by xemulat** [comment]
fixed
