### ISSUE TITLE
EchoX downloading after d9. 

### ISSUE THREAD

**Issue by sandeepvinnu** [xemulat/XToolbox#14]
![2022-12-28 13-56-53](https://user-images.githubusercontent.com/93006664/209782777-d6e67f01-ef6d-4016-aca9-d28ed723ae16.gif)
After "D9" the program is only downloading EchoX.bat. Ex. If I download SadCoy, it downloads. But if I go on after SadCoy like PrivateZilla. It downloads EchoX. Tested on 2 pcs now and both do the same thing. 

1. Go to 'Xtoolbox'
2. Type 'Anything above D9'
3. See error as it downloads EchoX

**Expected behavior**
See it download EchoX.bat after D9.

**Comment by imadraude** [comment]
same, applies to each menu

**Comment by xemulat** [comment]
fixed
