### ISSUE TITLE
[Feature Request] Add more linux distros!

### ISSUE THREAD

**Issue by Neglectfull** [xemulat/XToolbox#15]
**"Websites suck"- Albert Einstein**

### I don't want to keep going to the distro's website and this seems like it should be a good alternative (if you add them)

Add more, such as:

- Vanilla os
- Elementary os
- Linux Mint
- Manjaro
- Puppy os (i never used that os. i just like puppys.)

If u want me to get tortured and to not add more.... cheese
![e9ef14798ff84fa1afc705b034c18554-2667633080](https://user-images.githubusercontent.com/123305689/215811906-b7067ef7-b8d4-4330-a546-239bfcff7c0e.jpg)

**Comment by xemulat** [comment]
Okey!

**Comment by Neglectfull** [comment]
YEY!
