### ISSUE TITLE
XTBox.exe not opening

### ISSUE THREAD

**Issue by WR41THZ** [xemulat/XToolbox#19]
**Describe the bug**
I open the .exe file and nothing shows, and when i run it as admin nothing happens, the admin UAC doesn't even show.

**Expected behavior**
to open?

**Screenshots**
dont have a screenshot of nothing as it doesnt show anything.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version 2.3

**Comment by WR41THZ** [comment]
and yes i have python installed

**Comment by xemulat** [comment]
shit, idk

**Comment by xemulat** [comment]
should be fixed 👍

**Comment by vjaykrsna** [comment]
![Screenshot 2023-09-06 163951](https://github.com/xemulat/XToolbox/assets/68800521/f4af0150-e096-4b96-bb0c-1832bb47e9f4)
windows 11
latest version tbox
