### ISSUE TITLE
rather small issue but spelling error, users may be confused. Also a recommendation

### ISSUE THREAD

**Issue by Jordan231111** [xemulat/XToolbox#21]
rather small issue but spelled it wrong t11 sophiapp not spohiapp, users may be confused..

_Originally posted by @Jordan231111 in https://github.com/xemulat/XToolbox/issues/18#issuecomment-1512320371_
<img width="145" alt="Screenshot 2023-04-18 at 10 19 27 AM" src="https://user-images.githubusercontent.com/79342877/232806573-b6de76a9-e5bd-4864-99b3-a81dfe7b4015.png">

**Comment by Jordan231111** [comment]
Additionally recommend you add this somewhere, have been using this for years is extremely effective 

https://mega.nz/file/R14TjYwA#pGYLQge1RPPUYvYfjIGblzLDo2m3Ig_G1XetZiYqcpo    (credits to Adamx)


There is also something called CoutX made by the person that made EchoX not sure worth adding but something to know.

**Comment by xemulat** [comment]
1. spohi will be fixed in the next update
2. I will add CoutX
3. Mega.nz moment

**Comment by xemulat** [comment]
Issue closed, v2.5 released.
