### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by moritz-t-w** [xemulat/XToolbox#26]
**Describe the bug**
Whenever there's a Y/n prompt, the uppercase Y implies by convention that it is the default. However this is not the case here. When I hit enter without typing y or n it asks for an input.

**To Reproduce**
1. Run the tool
2. Select a thing to install
3. Press enter when the "Approve? (Y/n): " prompt appears

**Expected behavior**
Y default

**Desktop (please complete the following information):**
don't matter

**Comment by xemulat** [comment]
The uppercase `Y` doesn't imply that it's the default option.

**Comment by moritz-t-w** [comment]
Sure, that may just be my perception. However I don't know why the Y is uppercase in the first place. However that may be I think it's reasonable to make it the default anyways.

**Comment by xemulat** [comment]
I'll fix it as soon as it's possible on my end.

**Comment by xemulat** [comment]
I've got a pr, new release in max 2 business days
