### ISSUE TITLE
ERROR: Invalid requirement: pip install -U requests colorama lastversion ping3 filelock tqdm pip: error: no such option: -U

### ISSUE THREAD

**Issue by Drovosek01** [xemulat/XToolbox#27]
**Describe the bug**
Trying build https://github.com/xemulat/XToolbox#%EF%B8%8F-building and got error

**To Reproduce**
Did all that wrote in build section https://github.com/xemulat/XToolbox#%EF%B8%8F-building in Git bash in Windows
```
git clone https://github.com/xemulat/XToolbox
pip install -r requirements.txt
pip install pyinstaller
pyinstaller --onefile --clean --upx-dir="path\to\upx\dir" main.py
```
And when execute `pip install -r requirements.txt` I got error
```
$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Usage: pip [options]

ERROR: Invalid requirement: pip install -U requests colorama lastversion ping3 filelock tqdm
pip: error: no such option: -U
```

**Expected behavior**
Command for build execute without
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 x64
 - Python 3.11.1

**Comment by xemulat** [comment]
Just exclude the -U, I updated the file to fix this problem.
