### ISSUE TITLE
ERROR 3: Can't download file from the server...

### ISSUE THREAD

**Issue by Drovosek01** [xemulat/XToolbox#28]
**Describe the bug**
When try start ShutUp10 using cimmand D3 or other utilities -got error can't download file

**To Reproduce**
1. Go to release page and download [XTBox.exe](https://github.com/xemulat/XToolbox/releases/download/v2.8/XTBox.exe)
2. Run XTBox.exe using double click
3. Type D3 and press Enter and Enter

**Expected behavior**
Utility downloaded and launched.

**Screenshots**
![image](https://github.com/xemulat/XToolbox/assets/29478700/b0b7071f-e635-4770-ae88-8f3d9606ec2b)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 x64
 - Python 3.11.1

**Additional context**
If I copy direct link for download file and paste in browser it downloading without problems

**Comment by xemulat** [comment]
Thanks for the report, I've identified the issue, and I'll fix it in the next update.

**Comment by xemulat** [comment]
https://www.oo-software.com/en/shutup10

On the official site, you can't download it either, not a problem with my software. Sorry for the inconvenience.
