### ISSUE TITLE
Removal of DNG and introduction of ADV or Replacement of DNG to ADV

### ISSUE THREAD

**Issue by Jathurshan-2019** [xemulat/XToolbox#32]
I am the owner of the repository of Insider-Enroller. I find it is disturbing to see my repository as Dangerous as instead of Dangerous you can change this to Advanced.

Instead of adjective DNG that means Dangerous. You can use ADV which means Advanced.

**Comment by xemulat** [comment]
Yup, I'll do it as soon as possible!

**Comment by xemulat** [comment]
I'll release it in an update in about 1-2 days

**Comment by Jathurshan-2019** [comment]
tks
