### ISSUE TITLE
feature request: privacy.sexy

### ISSUE THREAD

**Issue by sudosign** [xemulat/XToolbox#36]
**Is your feature request related to a problem? Please describe.** no xtbox is working fine :)

**Describe the solution you'd like** integration of https://privacy.sexy/ software

**Describe alternatives you've considered** many alternatives are already implemented into the software

github link for software https://github.com/undergroundwires/privacy.sexy

nice job on this project!

**Comment by xemulat** [comment]
Hmmm, not a bad idea.

**Comment by sudosign** [comment]
i think a nice enhancement would be adding like a description, perhaps when u prompt the user if they want to download the application selected, u could gived like a brief description or like pull straight from their site or soemthing

also maybe 

1. bulk crap remover(i swear it was there before) 
2. ide such as: vscode/vscodium(privacy focused fork, https://vscodium.com/)/codium(privacy focused and optimized fork, https://thorium.rocks/codium/)
3. dns client like nextdns or simplednscrypt
4. browsers and settings like: tor, mullvad, waterfox, or maybe betterfox and arkenfox user.js

**Comment by xemulat** [comment]
That's a very good idea. I'll add DNS related quick settings in the next update (@furkan-o's idea) alongside with VSCodium and BCR. I don't think adding more firefox based browsers (and user.js) is essentially a good idea because there are simply too many of them. Also Floorp (my browser of choice) has a built in user.js switcher. Adding a description to every download would be too much of a hassle but I'll see what I can do. I'm cooking up a new project at the moment but these additions will be a nice break from writing React all week.

**Comment by furkan-o** [comment]
i think you're going to come out of the React abyss and take a breath. our working hours don't match but if u ping me on DC, i'm ready to help with development of xtoolbox. 
btw, most apps are now registered on winget. in the next version (4.1 or 4.2 or next gen u decide) u could reduce the size of tool by calling supported apps on winget. i'll report the result when i try. thanks again for this nice AIO.

**Comment by xemulat** [comment]
Sure, take into account that not every device has winget installed.

**Comment by furkan-o** [comment]
actually, winget comes as standard from win10 2004, but i never thought about those who use edited iso and older win10 versions. so, u're right.

**Comment by sudosign** [comment]
i also found https://wpd.app/ it has a few things that privacy.sexy doesn't but it is very lacking in updates ( 10-17-2021 last update) but in their discord

> Vegetorius — 03/07/2024 9:25 AM
> Yeah! according to the latest news, my colleague finally has time :wavy: 
> No ETA. But I'm already working.

so some updates soon i think

> I don't think adding more firefox based browsers (and user.js) is essentially a good idea because there are simply too many of them. Also Floorp (my browser of choice) has a built in user.js switcher. 

yeah makes sense it would just have too many browsers

> Adding a description to every download would be too much of a hassle but I'll see what I can do. I'm cooking up a new project at the moment but these additions will be a nice break from writing React all week.

is there anyway i could help(with either the project or this desc feature)? imma bfr i dont have any xp but i think it would be cool to learn as long as i dont break all of it

**Comment by xemulat** [comment]
> i also found https://wpd.app/ it has a few things that privacy.sexy doesn't but it is very lacking in updates ( 10-17-2021 last update) but in their discord
> 
> > Vegetorius — 03/07/2024 9:25 AM
> > Yeah! according to the latest news, my colleague finally has time :wavy:
> > No ETA. But I'm already working.
> 
> so some updates soon i think
> 
> > I don't think adding more firefox based browsers (and user.js) is essentially a good idea because there are simply too many of them. Also Floorp (my browser of choice) has a built in user.js switcher.
> 
> yeah makes sense it would just have too many browsers
> 
> > Adding a description to every download would be too much of a hassle but I'll see what I can do. I'm cooking up a new project at the moment but these additions will be a nice break from writing React all week.
> 
> is there anyway i could help(with either the project or this desc feature)? imma bfr i dont have any xp but i think it would be cool to learn as long as i dont break all of it

Sure, why not. You have to download this repo (as a zip, not using git clone), open in vscode and install all dependencies. Then you can take the help ui and mold it into shape of a privacy.sexy script wrapper. You can use this awesome library called rich to simplify the process of creating tables. Then you can do a pull request for this feature. If you have any questions feel free to ask me on discord, `@xemu.lated`

**Comment by xemulat** [comment]
Merged, in v4.1
