### ISSUE TITLE
Option D10 is not working (sweetylite)

### ISSUE THREAD

**Issue by Jordan231111** [xemulat/XToolbox#6]
![XTBox_G9e8V9RSre](https://user-images.githubusercontent.com/79342877/200212798-903cef4c-2c80-4a9b-8ac5-ae0ba5ac836b.png)

**Comment by xemulat** [comment]
Thanks for reporting the bug, i'll fix it.

**Comment by xemulat** [comment]
The backup url is `https://raw.githubusercontent.com/xemulat/MyFilesForDDL/main/SweetyLite2.bat`.

**Comment by xemulat** [comment]
Fixed
