### ISSUE TITLE
XTbox crashes after agreeing to the EULA

### ISSUE THREAD

**Issue by iy9k** [xemulat/XToolbox#7]
how do i fix the crash?

**Comment by iy9k** [comment]
turns out the crash happens if it opens using terminal (windows 11 version of cmd) instead of cmd

**Comment by xemulat** [comment]
Hmmm, i'll try to reproduce this glitch

**Comment by xemulat** [comment]
Nope, it doesn't crash for me.

**Comment by xemulat** [comment]
Issue stalled, OP won't respond
