### ISSUE TITLE
option T7 doesnt download (winaero tweaker)

### ISSUE THREAD

**Issue by iy9k** [xemulat/XToolbox#8]
**Describe the bug**
self explanatory from title

**To Reproduce**
1. try downloading t7 (winaerotweaker)
2. u will find it not download

**Expected behavior**
winaerotweaker should/shouldve download/downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/65314101/201473173-62d4db36-6ac8-4910-8719-331c80c6c20c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 22H2 (OS Build 22623.875)

**Additional context**
seems like its the case with more than other options, instead of just winaerotweaker

**Comment by xemulat** [comment]
Backup url `https://winaerotweaker.com/download/winaerotweaker.zip`
Fixed in v1.9

**Comment by xemulat** [comment]
Fixed
