### ISSUE TITLE
XTBox.exe - System Error This program can't start bc whatever.dll is missing from your computer

### ISSUE THREAD

**Issue by Ahmed3457** [xemulat/XToolbox#9]
i tried to start the program and this message popped up 

![image](https://user-images.githubusercontent.com/93637332/201532032-b9cca521-e4fd-466f-8f1f-d7644db192f0.png)

i tried running sfc /scannow and everything seems fine 

i have python installed 

i am running windows 7 x64
cpu: intel core i3-2350M
gpu: intel hd 3000
ram: 4 gb 

i am trying to try the program so i can help my friend and fix his preformance issues

**Comment by Ahmed3457** [comment]
i tried downloading the source code ([XTbox.py](XTbox.py)) and running it after installing all the depencencies and this error popped up
![image](https://user-images.githubusercontent.com/93637332/201532636-76cbd8b3-3b34-46aa-a175-51b499001ed6.png),
for the dll error it appears that the program uses a dll in a newer version of python

**Comment by xemulat** [comment]
Bro, this program is for Windows 10-64x and 11... Not Windows 7... Try upgrading...

**Comment by xemulat** [comment]
Issue isn't important, windows 7 isn't supported by XTB, Microsoft and the Python compiler is use (Pyinstaller + UPX).
There is a warning about everything except for Windows 10 (64bit only) and Windows 11 isn't supported.

Best regards
- Xm
